<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/10/12 02:56:12

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=PrograIV',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
