<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/11/30 03:26:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=PrograIV',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
